### ISSUE TITLE
使用GPT_ACCESS_TOKENS时出现报错

### ISSUE THREAD

**Issue by islandcwj** [anyidea/chatgpt-dingtalk-bot#1]
通讯正常，但是服务器返回unhashable type: 'dict'，无法正常对话，账号正常，因为我这个账号是谷歌登录的，没办法用账号密码绑定，请教下这个问题有什么办法解决吗 @anyidea

**Comment by anyidea** [comment]
有更详细的错误信息么？目前账号密码使用没问题的

**Comment by islandcwj** [comment]
没有太多了，钉钉返回的就是unhashable type: 'dict'，我是用coookie获取ChatGPT的TOKENS，后端服务正常响应，但是只返回了unhashable type: 'dict'
![image](https://user-images.githubusercontent.com/98686800/225827419-438efa54-347c-4ee3-aeff-46d7084aab2b.png)

**Comment by anyidea** [comment]
已经修复了

**Comment by islandcwj** [comment]
@anyidea 大佬，牛逼
