### ISSUE TITLE
大佬，请问该项目还继续维护吗？

### ISSUE THREAD

**Issue by Timoshao** [anyidea/chatgpt-dingtalk-bot#11]
* chatgpt-dingtalk-bot version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by anyidea** [comment]
有问题可以提的，有时间就会解决

**Comment by Timoshao** [comment]
由于用的token模式部署的，当我在和机器人沟通时，其他同事同时也进行了提问，看到后台并不是新开了一个聊天，而是他的提问插入到了我的提问当中，这样的话就会导致我的问题上下文关联出现问题。
![image](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/108260847/aa30c153-cf04-4cd7-9620-1e872f9b5edd)

![image](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/108260847/2da6faa5-4b7d-4fc0-9215-b02b2b290d96)

**Comment by Timoshao** [comment]
另外看到别人提问 AI分支，请问大佬，AI分支在哪里 我没找到

**Comment by anyidea** [comment]
> 另外看到别人提问 AI分支，请问大佬，AI分支在哪里 我没找到

api分支

**Comment by Timoshao** [comment]
大佬这个是API分支？
填写一个账号能解决并发吗？
![image](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/108260847/35fed473-7981-4bd3-879d-e5aefdb8d47f)

**Comment by anyidea** [comment]
> 大佬这个是API分支？
> 填写一个账号能解决并发吗？
> ![image](https://user-images.githubusercontent.com/108260847/245335620-35fed473-7981-4bd3-879d-e5aefdb8d47f.png)

api分支需要api key的，走的是openai官方接口，并发没问题的，你看下env文件需要填写的环境变量

**Comment by Timoshao** [comment]
请问大佬是这个文件吗？并没有看到API key字段
![image](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/108260847/43ecbc4c-16ab-4178-a299-9fef6885adad)

**Comment by anyidea** [comment]
> 请问大佬是这个文件吗？并没有看到API key字段
> ![image](https://user-images.githubusercontent.com/108260847/245339431-43ecbc4c-16ab-4178-a299-9fef6885adad.png)

GPT_API_KEY

**Comment by Timoshao** [comment]
docker部署GPT_API_KEY 模式的需要什么命令？
docker run -d --name=chatgpt-dingtalk-bot --restart unless-stopped -p 8090:8090 -e GPT_API_KEY=pWHlTb3CEznunIFS0Z5ET3BlbkFJFsWAscIdXXX  aidenlu/chatgpt-dingtalk-bot 
我用上面的命令部署之后 钉钉发送消息收不到回复，后台也没报错。

**Comment by anyidea** [comment]
目前api_key模式暂不支持docker部署，没有上传镜像

**Comment by Timoshao** [comment]
> 目前api_key模式暂不支持docker部署，没有上传镜像

大佬 能抽时间搞下api_key模式的docker吗

**Comment by anyidea** [comment]
> > 目前api_key模式暂不支持docker部署，没有上传镜像
> 
> 大佬 能抽时间搞下api_key模式的docker吗

你可以先自己构建镜像， 运行时候把环境变量加上去就行

**Comment by Timoshao** [comment]
大佬, 不是科班出身，不太董这个。刚学会用docker,能否抽时间搞下呢

**Comment by yandaty** [comment]
大佬我也求搞一个docker api分支。

**Comment by anyidea** [comment]
api分支已经发布了，可以这样运行
```
docker run -d --name=chatgpt-dingtalk-bot --restart unless-stopped -p 8090:8090 \
-e GPT_API_KEY=<key> \
-e GPT_MODEL=gpt-3.5-turbo \
aidenlu/chatgpt-dingtalk-bot:api
```

**Comment by Timoshao** [comment]
> api分支已经发布了，可以这样运行
> 
> ```
> docker run -d --name=chatgpt-dingtalk-bot --restart unless-stopped -p 8090:8090 \
> -e GPT_API_KEY=<key> \
> -e GPT_MODEL=gpt-3.5-turbo \
> aidenlu/chatgpt-dingtalk-bot:api
> ```
谢谢大佬 已经部署成功了
