### ISSUE TITLE
聊天机器人对话会相互串回答

### ISSUE THREAD

**Issue by yandaty** [anyidea/chatgpt-dingtalk-bot#13]
* chatgpt-dingtalk-bot version:0.4.9
* Docker version ：24.0.2
* Operating System:22

### Description

钉钉机器人多人聊天有时候会串问题，A问的问题，回答到B身上。之前使用token也是出现相同的问题，以为是token问题，换成刚刚发布的docker  api分支后，依然如此。求修复

### What I Did

```
![image](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/44827295/3217cd43-f0a4-4bb9-aaa5-360ca788920d)

```

**Comment by anyidea** [comment]
刚发了一版，可以测试下api分支是否正常了
