### ISSUE TITLE
API 版本输入”帮助“无菜单项

### ISSUE THREAD

**Issue by Timoshao** [anyidea/chatgpt-dingtalk-bot#14]
* chatgpt-dingtalk-bot version: 
docker api最新版
* Python version:3.9
* Operating System: centos

### Description
token版本输入“帮助”有菜单。
API版本输入“帮助“无菜单
![image](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/108260847/c01ef54f-7eb3-4ca8-9b75-9c5bfacb1e84)
![image](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/108260847/b7be41eb-b58c-45b1-9b78-a9bef8e83fcc)

### What I Did
API需要实现帮助菜单，有时候换一个话题 需要重新开始 不需要关联之前的上下文

**Comment by anyidea** [comment]
已修复

**Comment by Timoshao** [comment]
> 已修复
刚刚拉取最新的镜像 部署之后 发消息报错
![image](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/108260847/5d54ceb4-b57a-4c6f-8d96-4e696fcdbe47)

**Comment by Timoshao** [comment]
额 又重启了一遍一切正常
