### ISSUE TITLE
大佬，请问考虑实现打字机效果吗？

### ISSUE THREAD

**Issue by Timoshao** [anyidea/chatgpt-dingtalk-bot#15]
* chatgpt-dingtalk-bot version:
* Python version:
* Operating System:

### Description
听说钉钉机器人stream  支持打字机效果，请问有计划考虑支持吗？

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by anyidea** [comment]
能贴一下相关文档么，目前没有找到stream 支持打字机效果的文档

**Comment by Timoshao** [comment]
> 能贴一下相关文档么，目前没有找到stream 支持打字机效果的文档
大佬 你看下是否是这个文档。我之前加过另外一个钉钉项目的群，群里都在讨论这个模式能实现打字机效果
https://developers.dingtalk.com/document/resourcedownload/Introduction-to-stream-mode

**Comment by anyidea** [comment]
> > 能贴一下相关文档么，目前没有找到stream 支持打字机效果的文档
> > 大佬 你看下是否是这个文档。我之前加过另外一个钉钉项目的群，群里都在讨论这个模式能实现打字机效果
> > https://developers.dingtalk.com/document/resourcedownload/Introduction-to-stream-mode

刚才试了下 已经实现了， 晚点儿发一版支持下，需要配置钉钉app_key和app_secret

**Comment by Timoshao** [comment]
> > > 能贴一下相关文档么，目前没有找到stream 支持打字机效果的文档
> > > 大佬 你看下是否是这个文档。我之前加过另外一个钉钉项目的群，群里都在讨论这个模式能实现打字机效果
> > > https://developers.dingtalk.com/document/resourcedownload/Introduction-to-stream-mode
> 
> 刚才试了下 已经实现了， 晚点儿发一版支持下，需要配置钉钉app_key和app_secret

大佬牛逼，期待更新

**Comment by anyidea** [comment]
> > > > 能贴一下相关文档么，目前没有找到stream 支持打字机效果的文档
> > > > 大佬 你看下是否是这个文档。我之前加过另外一个钉钉项目的群，群里都在讨论这个模式能实现打字机效果
> > > > https://developers.dingtalk.com/document/resourcedownload/Introduction-to-stream-mode
> > 
> > 
> > 刚才试了下 已经实现了， 晚点儿发一版支持下，需要配置钉钉app_key和app_secret
> 
> 大佬牛逼，期待更新

api最新分支已经支持, 参考对应分支README使用

**Comment by Timoshao** [comment]
> > > > > 能贴一下相关文档么，目前没有找到stream 支持打字机效果的文档
> > > > > 大佬 你看下是否是这个文档。我之前加过另外一个钉钉项目的群，群里都在讨论这个模式能实现打字机效果
> > > > > https://developers.dingtalk.com/document/resourcedownload/Introduction-to-stream-mode
> > > 
> > > 
> > > 刚才试了下 已经实现了， 晚点儿发一版支持下，需要配置钉钉app_key和app_secret
> > 
> > 
> > 大佬牛逼，期待更新
> 
> api最新分支已经支持, 参考对应分支README使用

感谢大佬，已经成功的将原来的机器人转为支持stream的机器人
