### ISSUE TITLE
请问如何对接机器人

### ISSUE THREAD

**Issue by yandaty** [anyidea/chatgpt-dingtalk-bot#16]
大佬威武，太厉害了，居然实现如此酷炫的功能。

但是我尝试对接机器人的时候，发现不知道怎么对接，因为stream不同于http模式，无需公网IP，应该用AppKey/AppSecret以实现对接，然而我在看你教程的时候，却不知道哪里录入这些信息。

**Comment by yandaty** [comment]
docker run -d --name=chatgpt-dingtalk-bot --restart unless-stopped \
-e GPT_API_KEY=xxx \
-e GPT_MODEL=gpt-3.5-turbo \
-e DINGTALK_APP_KEY=xxx \
-e DINGTALK_APP_SECRET=xxx \
aidenlu/chatgpt-dingtalk-bot:api

这样执行可以吗？

**Comment by yandaty** [comment]
解决了，谢谢大佬，看日志，说没有权限调用接口，需要打开机器人的群聊和单聊权限才可以，大佬跪谢

**Comment by yandaty** [comment]
![image](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/44827295/a054af9b-e787-4cfd-96f2-8db42a5f60ed)

**Comment by yandaty** [comment]
很奇怪，我想用gpt-3.5-turbo-0301模型，发现无法聊天，之前都是可以的。

**Comment by anyidea** [comment]
l

> 很奇怪，我想用gpt-3.5-turbo-0301模型，发现无法聊天，之前都是可以的。

该模型近期应该是被openai废弃了，考虑使用gpt-3.5-turbo或gpt-3.5-turbo-0613

**Comment by Timoshao** [comment]
> l
> 
> > 很奇怪，我想用gpt-3.5-turbo-0301模型，发现无法聊天，之前都是可以的。
> 
> 该模型近期应该是被openai废弃了，考虑使用gpt-3.5-turbo或gpt-3.5-turbo-0613

token模式的考虑升级支持 stream吗 账号开通的有plus。API给员工用，token给老板用
