### ISSUE TITLE
关于stream模式消耗API咨询

### ISSUE THREAD

**Issue by Timoshao** [anyidea/chatgpt-dingtalk-bot#18]
* chatgpt-dingtalk-bot version:
* Python version:
* Operating System:

### Description

现在钉钉机器人是stream模式，但是发现消耗钉钉API比较多 能否优化。 公司用免费版的钉钉，只有1W的额度限制，照这样的消耗 还是只能用http模式机器人
![image](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/108260847/0b5a2d22-18de-4f26-a477-54eeff6890d0)

**Comment by Timoshao** [comment]
刚刚算了下 即使开通企业版钉钉 50W的额度 平均下来一天不到1.7W完 照这样消耗也不够用

**Comment by anyidea** [comment]
要实现打字机效果的话，就需要多次调用钉钉api刷新卡片内容，可以增加打字速度参数来控制接口调用频率，设置大一点可以减少接口调用次数

**Comment by Timoshao** [comment]
> 要实现打字机效果的话，就需要多次调用钉钉api刷新卡片内容，可以增加打字速度参数来控制接口调用频率，设置大一点可以减少接口调用次数
调用频率参数可以做成配置项吗？自己配置。1W的额度 如果全公司用 估计一天都不够

**Comment by Timoshao** [comment]
> 要实现打字机效果的话，就需要多次调用钉钉api刷新卡片内容，可以增加打字速度参数来控制接口调用频率，设置大一点可以减少接口调用次数

调用频率参数可以做成配置项吗？自己配置。1W的额度 如果全公司用 估计一天都不够

**Comment by anyidea** [comment]
目前可以通过参数DINGTALK_STREAM_SIZE来控制调用频率，越大调用频率越低

**Comment by Timoshao** [comment]
> 目前可以通过参数DINGTALK_STREAM_SIZE来控制调用频率，越大调用频率越低

已更新 请问这个参数设置的范围有限制吗？之前默认的是多少？

**Comment by Timoshao** [comment]
> > 目前可以通过参数DINGTALK_STREAM_SIZE来控制调用频率，越大调用频率越低
> 
> 已更新 请问这个参数设置的范围有限制吗？之前默认的是多少？
我设置成了100， 先出来一个字 ，然后又出来十几个字。
![image](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/108260847/5795b956-8edc-47ef-88e8-ff4352e894d5)

**Comment by anyidea** [comment]
DINGTALK_STREAM_SIZE 是机器人每次回复的字数，没有上限，越大可能等待时间久一点，打字连贯性差一点，越小消耗api调用次数多一点

**Comment by Timoshao** [comment]
> DINGTALK_STREAM_SIZE 是机器人每次回复的字数，没有上限，越大可能等待时间久一点，打字连贯性差一点，越小消耗api调用次数多一点

感谢大佬 已经设置1000，用完了切换回去http模式的
