### ISSUE TITLE
钉钉支持代码块的展示吗？

### ISSUE THREAD

**Issue by Timoshao** [anyidea/chatgpt-dingtalk-bot#19]
* chatgpt-dingtalk-bot version:
* Python version:
* Operating System:

### Description
目前的回复视乎bu'zhi不支持代码格式展示

![image](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/108260847/6fb79616-fd1a-4165-b268-2f6e751c3316)

### What I Did

![image](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/108260847/8c884c0c-72c0-46e7-9775-017d95b34251)

**Comment by anyidea** [comment]
钉钉对markdown支持的很有限，仅支持部分语法。

**Comment by Timoshao** [comment]
> 钉钉对markdown支持的很有限，仅支持部分语法。

好的 谢谢解惑
