### ISSUE TITLE
ACCESS_TOKENS还是存在问题

### ISSUE THREAD

**Issue by islandcwj** [anyidea/chatgpt-dingtalk-bot#2]
Client error '401 Unauthorized' for url 'https://bypass.duti.tech/api/conversation'
For more information check: https://httpstatuses.com/401

![image](https://user-images.githubusercontent.com/98686800/225835899-608c13de-0b11-4426-9763-8b2640d68cb2.png)
看样子是服务器需要进行身份验证

**Comment by anyidea** [comment]
这个是需要国外服务器部署或者挂代理服务器的，我刚才测试了ACCESS_TOKEN方式，可以正常提问

**Comment by islandcwj** [comment]
> 这个是需要国外服务器部署或者挂代理服务器的，我刚才测试了ACCESS_TOKEN方式，可以正常提问

当然，我是国外的服务器部署，不然我的账号密码也无法使用，你是获取哪个ACCESS_TOKEN,是我是这个
![image](https://user-images.githubusercontent.com/98686800/225838289-f213c911-267d-42e9-8631-cf3c5e3c16c4.png)

**Comment by anyidea** [comment]
README里面描述了access token获取方法， 直接访问这个就行 https://chat.openai.com/api/auth/session

**Comment by anyidea** [comment]
你拿的这个应该是session token我没开放这个参数

**Comment by islandcwj** [comment]
> 你拿的这个应该是session token我没开放这个参数

哦哦，可以了，问个问题access token多久过期？

**Comment by anyidea** [comment]
看了下接口，是一个月过期吧
