### ISSUE TITLE
请问https模式最后一个版本的docker镜像版本号是多少？

### ISSUE THREAD

**Issue by Timoshao** [anyidea/chatgpt-dingtalk-bot#20]
* chatgpt-dingtalk-bot version:
* Python version:
* Operating System:

### Description

如题，目前是stream版本，钉钉机器人https模式最后要一个版本号是多少呢？

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by Timoshao** [comment]
或者能否做成 自己配置stream模式还是https模式

**Comment by anyidea** [comment]
设置环境变量DINGTALK_STREAM_ENABLE=false就可以关闭了

**Comment by Timoshao** [comment]
> 设置环境变量DINGTALK_STREAM_ENABLE=false就可以关闭了

感谢，已经更新使用

**Comment by Timoshao** [comment]
> 设置环境变量DINGTALK_STREAM_ENABLE=false就可以关闭了

感谢，已经更新使用
