### ISSUE TITLE
token版突然不报错发送消息也没反应。

### ISSUE THREAD

**Issue by Timoshao** [anyidea/chatgpt-dingtalk-bot#23]
### Description

由于开通了plus会员，搭建有token版本，今天突然发送消息没反应，日志也没有报错，重新部署也是同样的问题。求大佬看下可能是啥问题
![image](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/108260847/615cfbb3-6ae7-48e8-8c9f-318df1a1d50c)

**Comment by Timoshao** [comment]
当我直接访问：http://IP:端口/chat 时，后台能看到请求记录。
![image](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/108260847/82bf6471-9384-4ff8-9905-94e394551015)

大概是因为，之前这样填写是正常的 现在为啥不可以了

![image](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/108260847/e06885e1-d892-417f-b163-9d63cf5d5d2f)
![image](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/108260847/5a2872f0-a178-40f6-a232-1b186d62aff7)


跪求大佬token模式也出一版stream模式的

**Comment by anyidea** [comment]
browser版本最近我没用了，这几天考虑重构下吧

**Comment by Timoshao** [comment]
> browser版本最近我没用了，这几天考虑重构下吧

感谢，主要是开通了plus会员，不用浪费了

**Comment by Timoshao** [comment]
不需要了
token转了api模式
