### ISSUE TITLE
Browser-Based模式，突然跑出以下錯誤

### ISSUE THREAD

**Issue by chenct1401** [anyidea/chatgpt-dingtalk-bot#25]
Field missing. Details: {'conversation_id': '1424a52a-9e1e-48c0-a99f-4bb577fbaa55', 'message_id': '357cbc84-d103-41c5-ac04-a72d47bdfa6a', 'is_completion': False, 'moderation_response': {'flagged': False, 'blocked': False, 'moderation_id': 'modr-7eMTgvVAzhICkTLFR4j9uk7h4lhrl'}}

今天下午才這樣，昨天都是好的。
.env檔使用下列三個參數
GPT_ACCESS_TOKENS=xxxxxxx
GPT_PAID=true
GPT_MODEL=gpt-4-0613
麻煩大大了，謝謝

**Comment by anyidea** [comment]
浏览器模式应该是暂不维护了，推荐 api 模式
