### ISSUE TITLE
大佬，能自定义请求地址BASE_URL吗？

### ISSUE THREAD

**Issue by Timoshao** [anyidea/chatgpt-dingtalk-bot#26]
### Description
目前很多API都是使用代理，不是默认的。能自定义请求地址BASE_URL

**Comment by furacas** [comment]
看了一下作者的当前实现是用的 https://github.com/acheong08/ChatGPT 中的v3
这个项目可以用环境变量设置BASE_URL的。 

以下为https://github.com/acheong08/ChatGPT v3.py中的源码
```
os.environ.get("API_URL") or "https://api.openai.com/v1/chat/completions",
```

**Comment by Timoshao** [comment]
> 看了一下作者的当前实现是用的 https://github.com/acheong08/ChatGPT 中的v3 这个项目可以用环境变量设置BASE_URL的。
> 
> 以下为https://github.com/acheong08/ChatGPT v3.py中的源码
> 
> ```
> os.environ.get("API_URL") or "https://api.openai.com/v1/chat/completions",
> ```

我不会写代码，不知道怎么修改。
我用过其他项目，BASE_URL设置配置项，默认是https://api.openai.com，可以自己配置。
所以希望大佬也做成配置项

**Comment by furacas** [comment]
环境变量设置一下API_URL即可。格式参考一下这个url https://api.openai.com/v1/chat/completions

**Comment by Timoshao** [comment]
![image](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/108260847/1475b06b-c534-4581-833a-0795df4cd30c)
大佬的配置参数没有这个字段，
如果在源码中修改 我又不会打包成docker

**Comment by anyidea** [comment]
已支持

**Comment by Timoshao** [comment]
> 已支持
大佬 有推送Docker镜像吗

**Comment by anyidea** [comment]
最新的api tag是支持的

**Comment by anyidea** [comment]
设置环境变量 GPT_API_URL

**Comment by Timoshao** [comment]
> 设置环境变量 GPT_API_URL
大佬 拉取了最新的镜像，设置了这个参数之后发消息后台报错了
![image](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/108260847/24df31a9-03bf-4824-a1d3-2e29217b4248)


![image](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/108260847/4b1b8ced-3f32-474d-a9a1-3faf11af9f29)

**Comment by Timoshao** [comment]
刚刚又试了下 还是不行。
GPT_API_URL在其他项目中设置的地址都可以用

**Comment by Timoshao** [comment]
搞好了 我的错
