### ISSUE TITLE
变量的设置问题

### ISSUE THREAD

**Issue by zhaolu1206** [anyidea/chatgpt-dingtalk-bot#28]
#GPT_TEMPERATURE=
#GPT_REPLY_COUNT=
#GPT_TRUNCATE_LIMIT=
请问这几个变量怎么设置？

**Comment by anyidea** [comment]
GPT_TEMPERATURE 这个控制 ai 的创造力（说白了就是胡编乱造能力，越高模型回答越能扯，低一点接近客观事实）
0-1 之间即可，用默认的也行
