### ISSUE TITLE
请求添加新模型

### ISSUE THREAD

**Issue by Timoshao** [anyidea/chatgpt-dingtalk-bot#29]
大佬，出了新模型是否还更新添加

**Comment by anyidea** [comment]
![CleanShot 2023-11-15 at 09 44 37@2x](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/48710760/d0e52ea7-7b39-4bbe-95a5-05c325e5ff58)
通过这个环境变量可以修改模型

**Comment by anyidea** [comment]
> 大佬，出了新模型是否还更新添加

是全新的模型吗？有具体名称吗？

**Comment by anyidea** [comment]
你可以提个 PR

**Comment by Timoshao** [comment]
> > 大佬，出了新模型是否还更新添加
> 
> 是全新的模型吗？有具体名称吗？

是的，最近的发布会新出了模型。比如
![image](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/108260847/87ab08bd-4d4f-4d84-b8d4-5f2c4eba2309)

https://openai.com/blog/new-models-and-developer-products-announced-at-devday

**Comment by anyidea** [comment]
近期会更新下新模型支持

**Comment by mason-home** [comment]
期待对新模型 gpt-4-1106-preview的支持。

**Comment by anyidea** [comment]
请升级最新版

**Comment by Timoshao** [comment]
> 请升级最新版

![image](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/108260847/16d0443e-29dc-4dea-b9e8-3fad5e0a4995)
更新之后 日志显示这个错误是啥原因呢？

**Comment by anyidea** [comment]
> > 请升级最新版
> 
> ![image](https://private-user-images.githubusercontent.com/108260847/292722843-16d0443e-29dc-4dea-b9e8-3fad5e0a4995.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDE1NDUsIm5iZiI6MTcwMzUwMTI0NSwicGF0aCI6Ii8xMDgyNjA4NDcvMjkyNzIyODQzLTE2ZDA0NDNlLTI5ZGMtNGRlYS1iOWU4LTNmYWQ1ZTBhNDk5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQxMDQ3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjQ3OTdlNjU0ZTZlYWEyYTdhZWU0MjM4MzMxYWE4ZjE1NTliZTE5MGQ0Yzc5ODQ0M2ExNWYzNWMwNmNlODBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4ALfUMjHK3OpsyujB0b8iA43qZB4g3vcGio49oIZits) 更新之后 日志显示这个错误是啥原因呢？

是最新镜像么，贴一下docker运行命令

**Comment by Timoshao** [comment]
> > > 请升级最新版
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/108260847/292722843-16d0443e-29dc-4dea-b9e8-3fad5e0a4995.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDE1NDUsIm5iZiI6MTcwMzUwMTI0NSwicGF0aCI6Ii8xMDgyNjA4NDcvMjkyNzIyODQzLTE2ZDA0NDNlLTI5ZGMtNGRlYS1iOWU4LTNmYWQ1ZTBhNDk5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQxMDQ3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjQ3OTdlNjU0ZTZlYWEyYTdhZWU0MjM4MzMxYWE4ZjE1NTliZTE5MGQ0Yzc5ODQ0M2ExNWYzNWMwNmNlODBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4ALfUMjHK3OpsyujB0b8iA43qZB4g3vcGio49oIZits) 更新之后 日志显示这个错误是啥原因呢？
> 
> 是最新镜像么，贴一下docker运行命令



> > > 请升级最新版
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/108260847/292722843-16d0443e-29dc-4dea-b9e8-3fad5e0a4995.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDE1NDUsIm5iZiI6MTcwMzUwMTI0NSwicGF0aCI6Ii8xMDgyNjA4NDcvMjkyNzIyODQzLTE2ZDA0NDNlLTI5ZGMtNGRlYS1iOWU4LTNmYWQ1ZTBhNDk5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQxMDQ3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjQ3OTdlNjU0ZTZlYWEyYTdhZWU0MjM4MzMxYWE4ZjE1NTliZTE5MGQ0Yzc5ODQ0M2ExNWYzNWMwNmNlODBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4ALfUMjHK3OpsyujB0b8iA43qZB4g3vcGio49oIZits) 更新之后 日志显示这个错误是啥原因呢？
> 
> 是最新镜像么，贴一下docker运行命令
我是用的portainer docker面板，先拉取最新镜像，然后再升级的。之前也是这样更新的没问题。

**Comment by Timoshao** [comment]
我是用的portainer docker面板，先拉取最新镜像，然后再升级的。之前也是这样更新的没问题。

**Comment by Timoshao** [comment]
> > > 请升级最新版
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/108260847/292722843-16d0443e-29dc-4dea-b9e8-3fad5e0a4995.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDE1NDUsIm5iZiI6MTcwMzUwMTI0NSwicGF0aCI6Ii8xMDgyNjA4NDcvMjkyNzIyODQzLTE2ZDA0NDNlLTI5ZGMtNGRlYS1iOWU4LTNmYWQ1ZTBhNDk5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQxMDQ3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjQ3OTdlNjU0ZTZlYWEyYTdhZWU0MjM4MzMxYWE4ZjE1NTliZTE5MGQ0Yzc5ODQ0M2ExNWYzNWMwNmNlODBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4ALfUMjHK3OpsyujB0b8iA43qZB4g3vcGio49oIZits) 更新之后 日志显示这个错误是啥原因呢？
> 
> 是最新镜像么，贴一下docker运行命令
docker run -d --name=yihu --restart unless-stopped -e GPT_API_KEY=sk-lUrhn3892a0442xxxx -e DINGTALK_APP_KEY=ding8b7exxxxxx -e DINGTALK_APP_SECRET=s6lzDRSkzTABAkz789xxxxx -e GPT_MODEL=gpt-3.5-turbo -e DINGTALK_STREAM_ENABLE=false -e DINGTALK_STREAM_SIZE=15 -e GPT_API_URL=http://xxxxx/v1/chat/completions aidenlu/chatgpt-dingtalk-bot:api
重新部署依然不行 提示错误如下
ModuleNotFoundError: No module named 'dingtalk_stream'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/chatbot/__main__.py", line 1, in <module>
    from .main import main
  File "/app/chatbot/main.py", line 3, in <module>
    from dingtalk_stream import AckMessage
ModuleNotFoundError: No module named 'dingtalk_stream'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/chatbot/__main__.py", line 1, in <module>
    from .main import main
  File "/app/chatbot/main.py", line 3, in <module>
    from dingtalk_stream import AckMessage
ModuleNotFoundError: No module named 'dingtalk_stream'
