### ISSUE TITLE
如何更新KEY？

### ISSUE THREAD

**Issue by tony-wang1992** [anyidea/chatgpt-dingtalk-bot#30]
* chatgpt-dingtalk-bot version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by anyidea** [comment]
是 openai 的 api_key么？ 可以通过环境变量来设置
![CleanShot 2023-11-30 at 10 07 25@2x](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/48710760/4934a43d-2ae3-4574-ae28-be7a183a935a)

**Comment by anyidea** [comment]
0.6.0已经支持了
