### ISSUE TITLE
ModuleNotFoundError: No module named 'dingtalk_stream'

### ISSUE THREAD

**Issue by tony-wang1992** [anyidea/chatgpt-dingtalk-bot#31]
* chatgpt-dingtalk-bot version:V0.6.6
* Python version:Python 3.6.8
* Operating System:宝塔面板7.9 [Centos8/LNMP]

### Description
容器安装后停止运行，并且无法重新启动，查看日志反馈遇到的问题是：ModuleNotFoundError: No module named 'dingtalk_stream'

### What I Did
在代码页面https://github.com/anyidea/chatgpt-dingtalk-bot.git下载了.env.dist文件上传至/root/chatgpt/chatgpt-dingtalk-bot-api文件夹，修改文件内环境变量，并重命名为.env
使用安装命令安装：
docker run -d --name=chatgpt-dingtalk-bot --restart=unless-stopped \
--env-file .env \
aidenlu/chatgpt-dingtalk-bot:latest
反馈安装成功，但是容器无法运行起来。

**Comment by tony-wang1992** [comment]
难道是我Python版本太低了？我之前安装成功使用过，删除重新按装出现的问题，docker下安装的

**Comment by wangr0031** [comment]
建议试试python3.8以上

**Comment by anyidea** [comment]
> 难道是我Python版本太低了？我之前安装成功使用过，删除重新按装出现的问题，docker下安装的

镜像中的 python 版本已经设置好了的，跟host 机器 Python 版本无关

**Comment by albin3** [comment]
![image](https://github.com/anyidea/chatgpt-dingtalk-bot/assets/6190670/0a012c5c-aead-4839-994a-745916511071)
@anyidea 现在镜像里确实少这个包

**Comment by albin3** [comment]
aidenlu/chatgpt-dingtalk-bot:0.6.2 用这个版本可以
