### ISSUE TITLE
How can I use the api SECRET KEY to run this rot?

### ISSUE THREAD

**Issue by WENGIF** [anyidea/chatgpt-dingtalk-bot#4]
* chatgpt-dingtalk-bot version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by anyidea** [comment]
Api key is not yet supported at the moment.

**Comment by anyidea** [comment]
Please checkout to api branch to use api key mode
