### ISSUE TITLE
error code 502 Bad Gateway

### ISSUE THREAD

**Issue by chenct1401** [anyidea/chatgpt-dingtalk-bot#6]
如題，大家有出現同樣錯誤嗎
![image](https://user-images.githubusercontent.com/30627274/232288171-2580e9ab-a54c-4cd4-a569-4861846e8c05.png)

**Comment by houzl3416** [comment]
出现了，怎么解决呢

**Comment by houzl3416** [comment]
> 如題，大家有出現同樣錯誤嗎 ![image](https://user-images.githubusercontent.com/30627274/232288171-2580e9ab-a54c-4cd4-a569-4861846e8c05.png)

https://github.com/acheong08/ChatGPT/issues/1341

**Comment by anyidea** [comment]
@chenct1401 @houzl3416 正在解决中

**Comment by anyidea** [comment]
https://github.com/acheong08/ChatGPT/issues/1336

**Comment by houzl3416** [comment]
> acheong08/ChatGPT#1336

可以更新一下docker镜像么

**Comment by chenct1401** [comment]
請問一下，是否有找到解決辦法？

**Comment by chenct1401** [comment]
![image](https://user-images.githubusercontent.com/30627274/232732790-2adb6a6e-3c90-4e91-962f-d70ce365ebae.png)
回饋訊息改變了

**Comment by chenct1401** [comment]
![image](https://user-images.githubusercontent.com/30627274/232754397-608b0e76-e759-4bef-95c6-083c3a80b734.png)
錯誤改成523

**Comment by houzl3416** [comment]
> [acheong08/ChatGPT#1336](https://github.com/acheong08/ChatGPT/issues/1336)

好像更新了，大佬看下能不能用了

**Comment by chenct1401** [comment]
![image](https://user-images.githubusercontent.com/30627274/233256342-fb1d8fb6-0118-4673-8013-aa2bb2ccbf4f.png)
今日回傳訊息之前有出現過，我嘗試架go-chatgpt-api走proxy也是一樣的錯誤
再麻煩大大費心一下，謝謝

**Comment by houzl3416** [comment]
> ![image](https://user-images.githubusercontent.com/30627274/233256342-fb1d8fb6-0118-4673-8013-aa2bb2ccbf4f.png)
> 今日回傳訊息之前有出現過，我嘗試架go-chatgpt-api走proxy也是一樣的錯誤
> 再麻煩大大費心一下，謝謝

把revchatgpt更新到最新版就可以了

**Comment by chenct1401** [comment]
@houzl3416 有詳細的指令操作嗎？  謝謝

**Comment by chenct1401** [comment]
是否有人可以協助，加賴或是釘釘，謝謝，不好意思需大家協助。

**Comment by houzl3416** [comment]
> 是否有人可以協助，加賴或是釘釘，謝謝，不好意思需大家協助。

发一下你的钉钉联系方式

**Comment by chenct1401** [comment]
釘釘號 chenct1401  謝謝

**Comment by chenct1401** [comment]
pip install --upgrade revChatGPT
改用poetry後已可正常使用，謝謝~
