### ISSUE TITLE
启动成功，但是无法发送请求

### ISSUE THREAD

**Issue by houzl3416** [anyidea/chatgpt-dingtalk-bot#7]
<img width="895" alt="image" src="https://user-images.githubusercontent.com/33145210/232433315-8a6c6034-a32b-486c-971d-968478cba13b.png">

**Comment by houzl3416** [comment]
> <img alt="image" width="895" src="https://user-images.githubusercontent.com/33145210/232433315-8a6c6034-a32b-486c-971d-968478cba13b.png">

端口应该没问题，之前docker启动一直用的8090.麻烦大佬帮忙排查一下

**Comment by anyidea** [comment]
cf bypass server失效， 等待修复吧

**Comment by anyidea** [comment]
same issue #6
