### ISSUE TITLE
关于钉钉机器人配置的疑问

### ISSUE THREAD

**Issue by skisqibao** [anyidea/chatgpt-dingtalk-bot#8]
消息接收地址和服务器出口IP
这两个框中填的IP是同一个IP吗，没搞明白这俩东西怎么填
把服务部署在一个公网IP的机器上，服务器出口IP是这个机器的对外IP，消息接收地址是此服务的具体请求？区别在这吗，不知道我理解的对不对

**Comment by anyidea** [comment]
都填部署服务机器的IP地址就行
